# Generated by Django 2.1.7 on 2019-03-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190326_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
