# Generated by Django 2.1.7 on 2019-03-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile_mail_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSubscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mail_subscribed',
        ),
    ]
