# Generated by Django 2.1.7 on 2019-03-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190329_1308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailSubscribers',
            new_name='MailSubscriber',
        ),
    ]
