# Generated by Django 2.1.7 on 2019-03-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190329_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsubscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
