# Generated by Django 2.1.7 on 2019-03-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190329_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, choices=[('hindi', 'Hindi'), ('english', 'English')], max_length=10),
        ),
    ]
