# Generated by Django 2.1.7 on 2019-04-05 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_auto_20190403_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend',
            field=models.ManyToManyField(related_name='mates', to=settings.AUTH_USER_MODEL),
        ),
    ]
