# Generated by Django 2.1.7 on 2019-04-11 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_profile_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 15, 6, 33, 263211)),
        ),
    ]
