# Generated by Django 2.1.7 on 2019-04-11 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_profile_sub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 22, 31, 30, 476963)),
        ),
    ]
