# Generated by Django 2.1.7 on 2019-04-11 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190411_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 22, 32, 44, 462864)),
        ),
    ]
