# Generated by Django 2.1.7 on 2019-04-11 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190411_2232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moovie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='link',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 23, 11, 37, 277358)),
        ),
    ]
