# Generated by Django 2.1.7 on 2019-04-12 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190412_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='book_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 22, 33, 1, 327479)),
        ),
    ]
