# Generated by Django 2.1.7 on 2019-04-12 17:50

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190412_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='mates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 23, 20, 51, 940230)),
        ),
    ]
